### ISSUE TITLE
CLASS C

### ISSUE THREAD

**Issue by serdarsinanoglu** [sandeepmistry/pico-lorawan#22]
Hi,

I used "SX1262 LoRa Node Module for Raspberry Pi Pico" in ABP mode "Class A". 
I used Dragino Lig16 Gateway for  this project.  
How to use SX1262 with CLASS C Mode?

Can you help me.

Thank you.

**Comment by sandeepmistry** [comment]
Hello @serdarsinanoglu.

This library currently does not support the SX1262 (however PR #15 is open to add support).

For the SX1276, the class can be changed here: https://github.com/ArmDeveloperEcosystem/lorawan-library-for-pico/blob/main/src/lorawan.c#L47

**Comment by serdarsinanoglu** [comment]
Thank you.
