### ISSUE TITLE
Lora example

### ISSUE THREAD

**Issue by noutram-old-uopaccount** [sandeepmistry/pico-lorawan#38]
If I don't want the complexity of LoRaWAN, are there any examples for simpler Lora communication?

**Comment by sandeepmistry** [comment]
Hi @noutram,

I'm not aware of examples that offer LoRa communications, as the scope of this library is for LoRaWAN.

**Comment by noutram-old-uopaccount** [comment]
Hi

Thanks for getting back to me.

From the README, I assumed it was derived from https://github.com/Lora-net/LoRaMac-node which has LoRa examples, but for other boards. 

I'll probably have to think again as I've cooked far too much time on this already.

Nick
