### ISSUE TITLE
Is this compatble?

### ISSUE THREAD

**Issue by happytm** [sandeepmistry/pico-lorawan#4]
Hey sandeep,

Would this module based on SX1276 chip work with your library?

https://www.aliexpress.com/item/1005002115974180.html?spm=a2g0o.store_pc_groupList.8148356.61.1b0d6ccfcQ9oPl

Thanks.

**Comment by sandeepmistry** [comment]
Hi @happytm,

I haven't tried that module myself, but from the link you shared it should be compatible with this library.

Feel free to close this issue if your questions is answered.

**Comment by happytm** [comment]
Thank you Sandeep.
