### ISSUE TITLE
How to perform peer to peer communcation using Adafruit Feather RP2040 with RFM95 LoRa Radio - 915MHz 

### ISSUE THREAD

**Issue by aniruddhapal211316** [sandeepmistry/pico-lorawan#40]
How to connect **Adafruit Feather RP2040 with RFM95 LoRa Radio - 915MHz boards** [link ](https://www.adafruit.com/product/5714) in a **peer to peer connection for communication**. Using **Pico SDK library** [link ](https://github.com/raspberrypi/pico-sdk) for **RP2040** microcontroller and your library **[lorawan-library-for-pico](https://github.com/ArmDeveloperEcosystem/lorawan-library-for-pico)** for **RFM95 LoRa Radio**.

I want to create a peer to peer connection in which a **Adafruit Feather RP2040 with RFM95 Board** can connect to other **Adafruit Feather RP2040 with RFM95** without the need to connect to a **LORAWAN Network transmitted by a LORAWAN Tower**. **Each individual Board in the peer to peer connect should be able to transmit and receive messages to any board in the peer to peer connection.**

**Comment by sandeepmistry** [comment]
Hi @aniruddhapal211316,

This question/feature is out of scope for this library, as it's goal is to provide support for LoRaWAN communications.
