### ISSUE TITLE
frame counter lost after power cycle?

### ISSUE THREAD

**Issue by ioanfesteu** [sandeepmistry/pico-lorawan#42]
Hi, I would like to ask for help for my problem:

I am running the library without problems but  I am at the point I am looking to save battery energy. I managed to put my Pico in deep sleep mode but even in such a state it consumes about 1.8 mA which is way to much. So I was thinking to use an auxiliary mcu such as ATTiny85 to power off my Pico between  sensor readings (TinyML stuff) and LoRaWAN sessions then going in deep sleep mode (around 0.0047 mA).

After a power cycle I am not going to join again the network but instead I am invoking only `lorawan_init_otaa()` then send my payload when ready. Can anybody confirm that the` lorawan_init_otaa() ` is reseting the `FCntUp` to 0 or they are retrieving the last saved value (if saved)?

Thank you!

**Comment by ioanfesteu** [comment]
I can confirm that `FCntUp ` is stored. It was my code that messed things.
So, if anybody wants to power off the Pico to conserve battery this can be done with an external mcu then at startup only invoke `lorawan_init_otaa()` , whitout the join steps, and the context will be restored from the nvram.

**Comment by sandeepmistry** [comment]
@ioanfesteu thanks for the update, can this be closed now?

**Comment by ioanfesteu** [comment]
@sandeepmistry yes it can be closed, thank you.
