### ISSUE TITLE
per 2 Per communication 

### ISSUE THREAD

**Issue by JavaMan7** [sandeepmistry/pico-lorawan#45]
Hello I would like to know if this library can be used for p2p coms. if it is possible could someone make an example this would really help me out. I have been trying to get p2p working with the RFM95 for over a week now.

**Comment by artichoked1** [comment]
No this library is for LoRaWAN. It a port of an outdated version of LoRaMac-Node and seems to be abandoned. You could try [akshayabali/pico-lora](https://github.com/akshayabali/pico-lora). Or more recently, [radiolib](https://github.com/jgromes/RadioLib) can do both LORaWAN and LoRa P2P as well as a bunch of other stuff.
