### ISSUE TITLE
Sending wrong Device EUI and Join EUI

### ISSUE THREAD

**Issue by simeonyetarian** [sandeepmistry/pico-lorawan#8]
I've entered my Device EUI, Join EUI and App Key in config.h of the otaa_temperatur_led example but the data that the gateway receives contains a different Device EUI and Join EUI (which are both the same for some reason).

My config.h file:
![Screenshot from 2021-07-28 11-34-34](https://user-images.githubusercontent.com/88085549/127301583-a36ba4f6-74f3-424d-aeb1-5d9197e77c29.png)

Minicom output of the Raspberry Pico with RFM95W:
(This already shows the wrong Device EUI and Join EUI)
![Screenshot from 2021-07-28 11-33-43](https://user-images.githubusercontent.com/88085549/127301622-d2be5797-1646-4a37-abed-40a0d4f1db6b.png)

Live data from the gateway with the wrong Device EUI and Join EUI:
![Screenshot from 2021-07-28 11-33-35](https://user-images.githubusercontent.com/88085549/127301632-e2013954-2a8d-4f45-b8be-3da9afcc81b9.png)

I am using The Things Network V3 with EU868 configuration.
I've also tried to change LoraWAN MAC version and Regional parameters version in the TTN console, but this has no impact since the minicom output of the pico already shows the wrong Device EUI and Join EUI.

Is there anything I can do to fix this?

**Comment by tnakasaki** [comment]
I have been having the same issues, using US915 settings. I will post screenshots when I have time.

This issue only happens when compling on a Raspberry Pi 4. When I compile the uf2 on a Mac, the expected EUI values are transmitted.

simeonyetarian, which platform are you using to compile?

**Comment by simeonyetarian** [comment]
@tnakasaki Thanks for sharing that information! Indeed, I am compiling on a Raspberry Pi 4. Maybe I will try to compile on another device then

**Comment by simeonyetarian** [comment]
Update: I can confirm that compiling on a Windows machine instead of a Raspberry Pi works. 
So this seems to be specific to the Raspberry Pi

**Comment by tnakasaki** [comment]
Here are some screenshots that illustrate the aforementioned issue.
**cmake** and **make** were performed on a Raspberry Pi 4.

config.h

<img width="965" alt="config h" src="https://user-images.githubusercontent.com/155821/127486317-97dfe46a-f097-4705-b1cc-8823cb78ab6e.png">

**cmake** output (configuring for Adafruit's Feather RP2040 board)

![cmake_feather](https://user-images.githubusercontent.com/155821/127486413-81f9d155-07f9-4f32-b319-412f3c210e72.png)

Partial **make** output

![make](https://user-images.githubusercontent.com/155821/127486635-494991c1-5a7a-4ddf-9220-cd043f5d2807.png)


TTN gateway data. Note the incorrect values for both JoinEUI and DevEUI, 618A011029890110

![wrong_join_dev_eui](https://user-images.githubusercontent.com/155821/127486521-67f6be1a-c906-4893-9101-6373569bb669.png)

Also, in config.h, if **LORAWAN_DEVICE_EUI** is set to **NULL**,  a correct DevEUI will be transmitted. That is, the same value printed in the default_dev_eui example program. JoinEUI remains incorrect.

**Comment by tnakasaki** [comment]
These are screenshots of **cmake** and **make** performed on a Mac. This compilation produced an executable that functioned correctly.

**cmake**

![mac_cmake](https://user-images.githubusercontent.com/155821/127489850-78fad867-46bc-49fc-97c4-d0aa29815a13.png)

**make**

![mac_make](https://user-images.githubusercontent.com/155821/127489913-36e60764-877d-4cd3-9132-1825df5cc237.png)

**Comment by sandeepmistry** [comment]
@simeonyetarian @tnakasaki Looks like it might be related to the version on Arm GCC used.

Based on the screenshots @tnakasaki provided in https://github.com/ArmDeveloperEcosystem/lorawan-library-for-pico/issues/8#issuecomment-889052952, they were using `7.3.1` or `8.3.0` on the Raspberry Pi, but using `9.2.1` on the Mac.

Any chance you could try to use a newer compiler version on the Raspberry Pi?

@simeonyetarian could you please provide the compiler versions you were using Raspberry Pi vs Windows? Thanks.

**Comment by sandeepmistry** [comment]
Hi @simeonyetarian, @tnakasaki,

I've prepared pull request https://github.com/ArmDeveloperEcosystem/lorawan-library-for-pico/pull/12 to resolve this. It would be great if you could try out the change and provide any feedback.

**Comment by ThomasLeister** [comment]
I was facing the same issue with GCC 11.2.1 on Fedora Linux (x86).
The PR seems to solve it. With debug mode enabled, the correct DevEui and JoinEui are shown.

Joining the network is not yet working, but that is probably another issue ... ;-)

**Comment by sandeepmistry** [comment]
@ThomasLeister thanks for the feedback on PR #12! I've gone ahead an merged it.

**Comment by tnakasaki** [comment]
> Hi @simeonyetarian, @tnakasaki,
> 
> I've prepared pull request #12 to resolve this. It would be great if you could try out the change and provide any feedback.

Sorry for the late response,
I've compiled on the Raspberry Pi 4, using the same setup as above. JoinEUI and DevEUI transmit correctly. Thank you so much for your solution!
