### ISSUE TITLE
Build failure: Wrong version of LoraMac-node at commit e31d3c1

### ISSUE THREAD

**Issue by eriklundh** [sandeepmistry/pico-lorawan#9]
The latest commit e31d3c1 breaks the build since it refers symbols in a later release of Loramac-node.

This repo refers lib/LoRaMac-node @ 6ff4561, which does not build without compile errors.

**Reproduce by doing a fresh git clone:**
  git clone --recurse-submodules https://github.com/sandeepmistry/pico-lorawan.git 
or
 git clone --recurse-submodules https://github.com/ArmDeveloperEcosystem/lorawan-library-for-pico.git

[build] ../src/boards/rp2040/eeprom-board.c: In function 'EepromMcuReadBuffer':
build] ../src/boards/rp2040/eeprom-board.c:31:12: error: 'LMN_STATUS_OK' undeclared (first use in this function)
[build]    31 |     return LMN_STATUS_OK;
[build]       |            ^~~~~~~~~~~~~
[build] ../src/boards/rp2040/eeprom-board.c:31:12: note: each undeclared identifier is reported only once for each function it appears in
[build] ../src/boards/rp2040/eeprom-board.c: In function 'EepromMcuWriteBuffer':
[build] ../src/boards/rp2040/eeprom-board.c:38:12: error: 'LMN_STATUS_OK' undeclared (first use in this function)
[build]    38 |     return LMN_STATUS_OK;

**However this repo builds without compile errors with lib/LoRaMac-node @ 14a79d3 (release 4.5.2)**

**Comment by sandeepmistry** [comment]
@eriklundh thank you for reporting this.

I've fixed this in https://github.com/ArmDeveloperEcosystem/lorawan-library-for-pico/commit/e82afcbe410e83c61dee0b0d55cd5ce70d1ed159. For now, will stick to v4.5.1 of LoRaMac-node.

**Comment by sandeepmistry** [comment]
Closing as fixed with https://github.com/ArmDeveloperEcosystem/lorawan-library-for-pico/commit/e82afcbe410e83c61dee0b0d55cd5ce70d1ed159.
